# Generated by Django 5.0.6 on 2024-06-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='block',
            field=models.ManyToManyField(related_name='blocked', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='followed_by', to='api.userprofile'),
        ),
    ]
