# Generated by Django 5.0.6 on 2024-06-11 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comments_created_at_comments_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='created_date',
        ),
    ]
