# Generated by Django 5.0.6 on 2024-06-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_posts_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='created_date',
        ),
    ]
