# Generated by Django 5.0.6 on 2024-06-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_comments_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='created_date',
        ),
    ]
