# Generated by Django 5.0.6 on 2024-06-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_posts_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='post_image',
            field=models.ImageField(upload_to='stories'),
        ),
    ]
