# Generated by Django 5.0.6 on 2024-06-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_stories_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='stories'),
        ),
    ]
